### ISSUE TITLE
Could you guys implement sso with key cloak

### ISSUE THREAD

**Issue by SinghRajKr** [squareboat/nestjs-boilerplate#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vinayak25** [comment]
Hi @SinghRajKr, KeyCloak looks like implementation for some specific use-case. We have no plan to support some specific mechanism in the near future. Closing this issue. Please feel free to create a new issue if you have any query/doubt.

**Comment by vinayak25** [comment]
Hi @SinghRajKr, KeyCloak looks like implementation for some specific use-case. We have no plan to support some specific mechanism in the near future. Closing this issue. Please feel free to create a new issue if you have any query/doubt.
