### ISSUE TITLE
How to use this template as a basis and modify it for GraphQL 

### ISSUE THREAD

**Issue by ramandhingra** [squareboat/nestjs-boilerplate#22]
Could you pl. hint out how can I modify the existing  code and add GraphQL support? Great, if you give some ideas.

Thanks

**Comment by vinayak25** [comment]
Hi @ramandhingra, our boilerplate provides tools which you can use irrespective of what you use, REST APIs or GraphQL. NestJS provides integration with GraphQL out of the box. You can have a look at [here](https://docs.nestjs.com/graphql/quick-start) for more information on how to go about it.

**Comment by ramandhingra** [comment]
Thanks Vinayak, will have a look at it.
