### ISSUE TITLE
Is it possible to enhance database features with mongodb

### ISSUE THREAD

**Issue by weizy0219** [squareboat/nestjs-boilerplate#23]
I like this boilerplate very much. Honestly, there is not much active nestjs projects like this one.
However, I use mongodb in my project, and looking forward for this project to support mongodb. But as I am not clear with the backend ORM package, and not clear whether it is possible.

**Comment by vinayak25** [comment]
Hello @weizy0219, thank you for your kind words. Our love for NestJS is what keeps us to contributing it.

TBH, I have also been in the same spot for lack of support of MongoDB while I was working on one of my projects. I ejected objection and added support for MongoDB in the `core` library.

I am attaching the updated `core` lib package which has support for following things:
1. Alias Routes, to easily get qualified urls for route inside your project
2. Support for MongoDB repository.
3. And some bug fixes.

You can download the repo from the link mentioned below. Let me know incase if you have any questions.

[nestjs-boilerplate-mongo.zip](https://github.com/squareboat/nestjs-boilerplate/files/6183776/nestjs-boilerplate-mongo.zip)

**Comment by weizy0219** [comment]
@vinayak25 Thank you very much for your response, I've downloaded the file and try to use it in my project , I'll give a response back when I get some progress and will close the issue then.

**Comment by vinayak25** [comment]
Hello @weizy0219, please let me know if this worked for you
