### ISSUE TITLE
ADD : Support for console commands(CLI)

### ISSUE THREAD

**Issue by tanmaymohan** [squareboat/nestjs-boilerplate#3]
**Is your feature request related to a problem? Please describe.**
Add support for CLI applications

**Describe the solution you'd like**
The ability to run console commands in npm to run single-run only tasks.

**Describe alternatives you've considered**
None 

**Additional context**
N/A

**Comment by vinayak25** [comment]
Please check #5, shall be adding in the official documentation soon.
