### ISSUE TITLE
Update make:migration command documentation

### ISSUE THREAD

**Issue by maxmarkus** [squareboat/nestjs-boilerplate#35]
Hello 👋  

Thank you for this really nice pieces of software, perfectly suited for my side project. Hope this does not die unmaintained :-) 

Wasn't able to find the documentation repo, so I put it here. 

On https://squareboat.com/open-source/nestjs-boilerplate/database/migrations  the "Create new migration" the command should be updated, since the command interface does not have named attributes.

`node cli make:migration create_users_table`

Best, Markus

**Comment by vinayak25** [comment]
Thanks for reporting this @maxmarkus! I will fix this and let you know.
